### ISSUE TITLE
TEST_HOST should be set automatically

### ISSUE THREAD

**Issue by brentleyjones** [yonaskolb/XcodeGen#377] opened 2018-08-10 17:33 UTC
When a test has an app as a target it should set the `TEST_HOST` automatically. We need to make sure not to break UI tests though. Discussed here:  https://github.com/yonaskolb/XcodeGen/issues/372#issuecomment-411321621.

**Comment by yonaskolb** [comment] 2018-08-10 23:25
Somewhat related to #71

**Comment by yonaskolb** [comment] 2018-12-05 07:57
Duplicate of of #408

**Closed by yonaskolb** 2018-12-05 07:57 UTC
Labels: enhancement
