### ISSUE TITLE
Recursive path issues

### ISSUE THREAD

**Issue by iamtomcat** [yonaskolb/XcodeGen#260] opened 2018-03-01 23:23 UTC
When I move to the parent directory and then try and use other folder outside of the current directory, everything is picked up fine, however all the folders are not included inside of the named directory or the last folder.

I'm getting around this by using a symlink to pull the folders in correctly.

Should also note this happens when using a full path as well.

Using a symlink:
<img width="272" alt="screen shot 2018-03-01 at 3 21 21 pm" src="https://user-images.githubusercontent.com/6033483/36875334-62183080-1d64-11e8-89c4-f8b23e77d8e1.png">

Without symlink and using a parent path: `../otherfolder/sources`
<img width="266" alt="screen shot 2018-03-01 at 3 22 27 pm" src="https://user-images.githubusercontent.com/6033483/36875345-6e86bee0-1d64-11e8-832c-5edb4a1bd305.png">

**Comment by yonaskolb** [comment] 2018-03-01 23:28
Hi @iamtomcat 
Do you have an example spec, showing how you use source paths.
Are you using `fileGroups` or `options. createIntermediateGroups`?

**Comment by iamtomcat** [comment] 2018-03-01 23:46
Here is my spec. No I'm not using filegroups. Maybe that is what I'm missing in this case?
```
name: Generated
options:
  deploymentTarget: 
    iOS: "8.0"
  bundleIdPrefix: com.paywith
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
configs:
  Debug: debug
  Release: release
targets:
  PayWithSDKCoreFramework:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: /Users/tclark/projects/PayWithSDKCore/PayWithSDKCoreFramework/Info.plist
    sources: 
      - path: /Users/tclark/projects/PayWithSDKCore/Sources
        name: CheeseTown
      - path: ../PayWithSDKCore/PayWithSDKCore
  PayWithSDK:
    type: library.static
    platform: iOS
  PayWithSDKFramework:
    type: framework
    platform: iOS
  PayWithSDKMallRewards:
    type: framework
    platform: iOS
    #com.paywith.PayWithSDKMallRewards
    settings:
      INFOPLIST_FILE: "PayWithSDKMallRewards/Info.plist"
      GCC_PREPROCESSOR_DEFINITIONS: ["$(inherited)", "IS_NEW=1"]
    dependencies:
      - carthage: AirshipKit
      - target: PayWithSDKCoreFramework
    sources: 
      - Sources/Shared
      - path: PayWithSDKMallRewards
        excludes: # Add these to the project level manually till https://github.com/yonaskolb/XcodeGen/pull/252 is implemented
        - "QRCodeReaderViewController/*.[mh]"
  PayWithSDKFrameworkTests:
    type: bundle.unit-test
    platform: iOS
  PayWithSDKUniversal:
    type: tool 
    platform: iOS
    postbuildScripts:
      - path: Scripts/BuildFramework_Old.sh
  OCLint:
    type: tool
    platform: iOS
    postbuildScripts:
      - path: Scripts/OCLint.sh
    
```

**Comment by iamtomcat** [comment] 2018-03-02 00:18
Also is it possible to glob files together under one group?

**Comment by iamtomcat** [comment] 2018-03-05 18:18
@yonaskolb This might be related to this issue. I found that if a folder doesn't have any files in it then any folder inside of it gets pulled out into it's own group instead of being included.

**Comment by yonaskolb** [comment] 2018-05-25 22:49
Hi @iamtomcat, I’m reopening this as these are still valid issues. Sorry I haven’t gotten around to them yet, this fell under the radar.
Are you able to post an update about your learnings, and your workarounds?

**Comment by Alex293** [comment] 2018-05-26 14:50
I have the same issue :(

@iamtomcat  I don't have any workaround for now but let me now if I can do anything to help you find out what's going on. I have a starter project but it is in a private repo. I can add you if required

**Comment by iamtomcat** [comment] 2018-06-01 13:48
So what I do is kind of double up on a folder.

At the moment it's able to tell what has been included or not with original path and it should glob the rest up. Not the most ideal for being explicit.

```
- path: /path/to/stuff
- path: /path/to
  - visibility: project
```

**Comment by Alex293** [comment] 2018-06-01 16:07
@yonaskolb I'm trying to move things around to understand what I can do.
Juste to be sure all the paths in project.yml are supposed to be relative to location of : 
- project.yml 
- where xcodegen is run
- the project argument of xcodegen ?

**Comment by yonaskolb** [comment] 2018-06-03 07:59
All paths in the `project.yml` are designed to be relative to that file.
It looks like there may be issues when the project is not in the same directory as `project.yml`

**Comment by vgorloff** [comment] 2018-07-04 05:36
Here is what i have on my side when including sources outside of project dir .)

![s180704_0835141](https://user-images.githubusercontent.com/3200080/42258606-430ab646-7f65-11e8-8f1e-f9c6fc84effd.png)

**Comment by rpassis** [comment] 2018-11-03 02:29
I think I may have hit the same/similar issue here.

For a given configuration
```
  Shared:    
    type: framework
    platform: iOS
    dependencies:
      - carthage: RxSwift
    sources:      
      - path: Shared/Support
        name: Shared
        headerVisibility: project
      - path: Shared
```

I'm getting folders generated as:

```
MyProject
    |_ Shared
    |_ Shared
```

What I am looking for

```
MyProject
    |_ Shared
           |_ Support
```

Where the support folder contains header files with `project` visibility.

Am I doing something wrong?

Thanks!

**Comment by yonaskolb** [comment] 2018-11-03 02:39
I see. Thanks for the info @rpassis.
What happens if you set `createIntermediateGroups`?
```
options:
  createIntermediateGroups: true
```

**Comment by rpassis** [comment] 2018-11-03 02:43
Thanks @yonaskolb that solves it!

FWIW here's what I used

```
  Shared:    
    type: framework
    platform: iOS
    dependencies:
      - carthage: RxSwift
    sources:            
      - path: Shared/Support
        headerVisibility: project        
      - path: Shared
        excludes: 
        - "Support/*.[mh]"
```

**Comment by yonaskolb** [comment] 2018-11-03 02:55
Great! It's bit of a workaround I know.
Another future solution might something like this https://github.com/yonaskolb/XcodeGen/pull/187

**Comment by Alex293** [comment] 2018-12-22 12:52
I'm back on a project using XcodeGen. The issue is still here : 
With this folder arch : 
Project/project.yml
Project/SomeFolder/SomeSource
in Xcode I get SomeFolder/SomeSource

now if I move to: 
Project/Tools/project.yml
Project/SomeFolder/SomeSource
XCodeGen says that path aren't correct

so I move paths adding ../ in project.yml
XCodeGen says it's ok but in Xcode all folders are a the same level

**Comment by yonaskolb** [comment] 2019-10-27 12:30
2.10.0 has been released. Closing this for now. Please open again if anyone has any more issues with this

**Closed by yonaskolb** 2019-10-27 12:30 UTC
Labels: bug

**Comment by LiewJunTung** [comment] 2019-11-01 06:46
Can confirm it works if the folder is inside the directory with the `project.yml` file. However, it is not working if I use relative paths.

<img width="269" alt="Screenshot 2019-11-01 at 2 44 06 PM" src="https://user-images.githubusercontent.com/4220976/68007365-5877bb80-fcb6-11e9-8739-04ac3e8948bd.png">
<img width="251" alt="Screenshot 2019-11-01 at 2 43 44 PM" src="https://user-images.githubusercontent.com/4220976/68007368-5b72ac00-fcb6-11e9-883f-93ac1f83f1bd.png">
<img width="454" alt="Screenshot 2019-11-01 at 2 43 29 PM" src="https://user-images.githubusercontent.com/4220976/68007369-5c0b4280-fcb6-11e9-8687-8f6915c54f07.png">

**Comment by LiewJunTung** [comment] 2019-11-15 02:51
@yonaskolb @giginet
