### ISSUE TITLE
Feature Request: Support StoreKit Testing Configuration file in Scheme

### ISSUE THREAD

**Issue by gemmakbarlow** [yonaskolb/XcodeGen#944] opened 2020-09-02 19:57 UTC
StoreKit testing will shortly be available in Xcode 12, which requires support for a `Configuration.storekit` file to be mapped into a scheme.

An overview of the upcoming functionality can be found [via this WWDC video](https://developer.apple.com/videos/play/wwdc2020/10659/).

More specifics available [via this Apple Documentation](https://developer.apple.com/documentation/xcode/setting_up_storekit_testing_in_xcode).

**Comment by jcolicchio** [comment] 2020-10-08 01:56
I'm going to take a look at implementing this, I'd also like to see XcodeGen handle this 👍

**Comment by jcolicchio** [comment] 2020-10-08 03:15
This'll require an update to the underlying XcodeProj dependency to support `StoreKitConfigurationFileReference`, however I'm running into an issue with Carthage and Xcode 12 when trying to build and tweak XcodeProj :\

**Comment by gemmakbarlow** [comment] 2020-10-08 22:50
@jcolicchio What issue are you seeing ? I'd be happy to take a look also.

**Comment by jcolicchio** [comment] 2020-10-08 22:58
The issue is that we have no way of specifying a scheme's Store Kit Configuration in yaml, so this field always resets on generating the project:

<img width="486" alt="Screen Shot 2020-10-08 at 3 56 58 PM" src="https://user-images.githubusercontent.com/2837288/95521676-f6700d80-097e-11eb-98d2-7cdbebb29c4b.png">

In order for XcodeGen to populate this field, we'll need XcodeProj to support encoding and decoding the `StoreKitConfigurationFileReference` child of the scheme's `LaunchAction`.

I've got an open PR for XcodeProj, which I think will make the appropriate change to enable us to implement this functionality in XcodeGen: https://github.com/tuist/XcodeProj/pull/573

**Comment by jcolicchio** [comment] 2020-10-08 23:09
The issue I was seeing with Carthage was related to Xcode 12 and the `lipo` command, but I found a fix and I also learned that I needed to run `swift package generate-xcodeproj` :P

**Comment by jcolicchio** [comment] 2020-10-09 18:15
Currently blocked by #965 due to the fact that `simulateLocation` and `storeKitConfiguration` both require a relative path that differs depending on whether the project is opened directly vs as part of a `.xcworkspace` :/

**Comment by gemmakbarlow** [comment] 2020-10-10 22:45
> The issue I was seeing with Carthage was related to Xcode 12 and the `lipo` command, but I found a fix and I also learned that I needed to run `swift package generate-xcodeproj` :P

Nice work figuring that out.

**Comment by jcolicchio** [comment] 2020-10-10 23:13
> > The issue I was seeing with Carthage was related to Xcode 12 and the `lipo` command, but I found a fix and I also learned that I needed to run `swift package generate-xcodeproj` :P
> 
> Nice work figuring that out.

Literally on the README haha, but who actually reads instructions 🤷‍♂️

**Comment by jcolicchio** [comment] 2020-10-16 18:52
@gemmakbarlow PR is ready for review, hopefully we can support storekit configuration soon 🤞

**Comment by gemmakbarlow** [comment] 2020-10-17 17:43
Awesome work, and thank-you. This is looking 💯

**Comment by FelixII** [comment] 2021-02-12 18:45
Is there anything new on this topic? I would love to integrate StoreKit testing into my project as well. 👍

**Comment by jcolicchio** [comment] 2021-02-12 23:13
@FelixII I've been trying to keep this PR up to date, and need a second reviewer in order to merge; would you be so kind?

**Comment by FelixII** [comment] 2021-02-13 20:14
@jcolicchio Sure, I can build the PR branch on my device and check if it works with my project. But I've only been using XcodeGen for a few days and am not familiar with the source code at all. Therefore I can't do a proper code review.

**Comment by yonaskolb** [comment] 2021-02-15 00:59
Merged! Will be a release hopefully today

**Closed by yonaskolb** 2021-02-15 00:59 UTC

**Comment by FelixII** [comment] 2021-02-22 09:41
@yonaskolb Any updates on the release?
