### ISSUE TITLE
Seeing homebrew build issues with 0.6.1

### ISSUE THREAD

**Issue by ehyche** [yonaskolb/XcodeGen#58] opened 2017-09-18 19:29 UTC
I have Xcode 9 GM installed, and have ensured that I am using them from the command-line. When I do the following homebrew commands:

```
        brew update
        brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
        brew install XcodeGen
```

then I am getting the following errors both on my local laptop and our CI servers:

```
Updated 2 taps (caskroom/cask, homebrew/core).
==> New Formulae
azure-cli@1
json-table
==> Updated Formulae
akamai
angular-cli
apache-opennlp
axel
azure-cli
bandcamp-dl
...
webpack
wpscan
xorriso
xtensor
you-get
youtube-dl
==> Deleted Formulae
kes
==> Tapping yonaskolb/xcodegen
Cloning into '/usr/local/Homebrew/Library/Taps/yonaskolb/homebrew-xcodegen'...
Tapped 1 formula (99 files, 2.7MB)
==> Installing xcodegen from yonaskolb/xcodegen
==> Downloading https://github.com/yonaskolb/XcodeGen/archive/0.6.1.tar.gz
==> Downloading from https://codeload.github.com/yonaskolb/XcodeGen/tar.gz/0.6.1
==> Building XcodeGen
==> swift build -c release -Xlinker -rpath -Xlinker @executable_path -Xswiftc -static-stdlib
Last 15 lines from /Users/builduser/Library/Logs/Homebrew/xcodegen/01.swift:
2017-09-18 18:59:50 +0000

swift build -c release -Xlinker -rpath -Xlinker @executable_path -Xswiftc -static-stdlib

error: manifest parse error(s):
sandbox-exec: sandbox_apply_container: Operation not permitted

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
yonaskolb/xcodegen

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed! curl: (22) The requested URL returned error: 422 Unprocessable Entity (GitHub::Error)
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:284:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:231:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:244:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:26:in `<main>'
```

**Comment by yonaskolb** [comment] 2017-09-18 20:14
Duplicate of #51
I've just done a 1.0.0 release with Swift 4 support, but this still seems to be a problem...
It seems something must be updated in the package or build script, though not sure what yet

**Comment by yonaskolb** [comment] 2017-09-18 20:59
Move discussion into #51

**Closed by yonaskolb** 2017-09-18 20:59 UTC
