### ISSUE TITLE
fileGroups makes duplicate top level groups

### ISSUE THREAD

**Issue by keith** [yonaskolb/XcodeGen#150] opened 2017-11-14 06:59 UTC
With this project config:

```yaml
name: Project
fileGroups:
  - Sources
targets:
  Project:
    type: application
    platform: iOS
    sources:
      - Sources
```

And this directory structure:

```
% tree
.
├── Sources
│   ├── Foo
│   │   ├── Foo
│   │   │   └── bar.swift
│   │   └── baz.swift
│   └── foo.swift
└── project.yml

3 directories, 4 files
```

You end up with duplicate top level groups named `Foo`:

![image](https://user-images.githubusercontent.com/283886/32766975-3ab04f2a-c8c6-11e7-8653-685376317ec4.png)

Where the structure should actually match the files on disk.

Example project: [XcodeGenTest.zip](https://github.com/yonaskolb/XcodeGen/files/1469821/XcodeGenTest.zip)

**Comment by keith** [comment] 2017-11-14 07:00
Looks like this also happens if you set `createIntermediateGroups: True`

**Comment by yonaskolb** [comment] 2017-11-14 10:47
On it!

**Comment by yonaskolb** [comment] 2017-11-14 11:06
@keith I can't reproduce this, either in a test or your example project. Is this off master?

**Comment by keith** [comment] 2017-11-14 16:51
This happens for me off master (e8188ad9f825f6cc978f55721f1c68d150d4f399) yes

**Comment by yonaskolb** [comment] 2017-11-14 19:31
Strange. I've run it on the exact project you attached with success...

<img width="171" alt="screen shot 2017-11-14 at 8 28 45 pm" src="https://user-images.githubusercontent.com/2393781/32800400-80a30c66-c97a-11e7-9c19-6c2c6f36c871.png">

I've also just committed a passing test to master

**Comment by yonaskolb** [comment] 2017-11-15 00:45
If you're still seeing this @keith, could you submit a failing test?

**Comment by keith** [comment] 2017-11-15 00:53
I don't think the test added here https://github.com/yonaskolb/XcodeGen/commit/2c1789f71760f62df3458318a391ed58f8774d19 actually tests the problem. In my case the sources are still correctly added with their correct source paths to the compile build phase, it's just that the groups are wrong. I'm still seeing this after a clean build on master, trying to dig in and see why it's not happening for you.

**Comment by yonaskolb** [comment] 2017-11-15 00:59
If the directories looked like they do in your screenshot that test should fail, as the nest navigates down into the groups

**Comment by keith** [comment] 2017-11-15 01:34
It looks like the project that is generated by the tests (if I write it out manually) works correctly for me as well. So I'm not sure what the difference is.

**Comment by yonaskolb** [comment] 2017-11-15 13:25
I was able to reproduce the issue! I did it by running xcodegen from within the project directory you sent me. I was running it from another directory before (an xcode build directory with --path and --project arguments pointing to your project)
So it's something to do with relative paths

**Closed** 2017-11-15 13:59 UTC

**Comment by keith** [comment] 2017-11-15 15:13
Aha! Phew, I’m not crazy. Thanks!

**Comment by yonaskolb** [comment] 2017-11-15 15:15
I'm surprised no one else found that during this release preperation
