### ISSUE TITLE
Optional path not working

### ISSUE THREAD

**Issue by KyoheiG3** [yonaskolb/XcodeGen#546] opened 2019-03-27 04:52 UTC
Hi.
Following project spec should make optional file reference, but it's not made.

```yml
name: MyProject
targets:
  MyFramework:
    platform: iOS
    type: framework
    sources:
      - path: Sources
      - path: Sources/File.swift
        optional: true
```

#527 might be related.

xcodegen 2.3.0

Thanks.

**Comment by yonaskolb** [comment] 2019-03-27 09:40
Hi @KyoheiG3. Could you explain your issue a bit more?
The `optional` property just controls whether XcodeGen will fail or not if the source is missing. It's doesn't make "optional file references" as you say

**Comment by KyoheiG3** [comment] 2019-03-28 02:43
If create the above `project.yml` and execute xcodegen in the following file tree state:

<img width="389" src="https://user-images.githubusercontent.com/5707132/55124771-c40b1080-514a-11e9-8c54-b894b1a230b1.png">

I need the file reference to be created even if the file doesn't actually exist.

<img width="156" src="https://user-images.githubusercontent.com/5707132/55125058-d76aab80-514b-11e9-9390-f99cf2159cc8.png">

But, executing xcodegen does not create a file reference (`File.swift`). This is from version `2.3.0`. The reason why I need the file reference is that the file may actually be created by a script etc in the build phase of xcode.
For example, run swiftgen in the build phase.

**Comment by yonaskolb** [comment] 2019-03-29 10:53
Oh I see. The `optional` property doesn't cater for that. As mentioned in https://github.com/yonaskolb/XcodeGen/pull/547 I would suggest running your other generation scripts before xcodegen. This issue tracks adding a `preGen` hook https://github.com/yonaskolb/XcodeGen/issues/479, but for now you can just add the script to a `generate.sh` script or something

**Comment by KyoheiG3** [comment] 2019-03-31 10:30
Thank you for your reply. I'll wait to be merged #479.

**Comment by ra1028** [comment] 2019-04-02 04:58
@yonaskolb 

I don't agree to close this issue.
Running the generator tool such as SwiftGen in `preGen` hook, slows down the execution of frequently executed `xcodegen`, and it's redundant because it executed even in the build phase.

Also, that a file is missing isn't an error, IMO.
It means a reference to the file that should be.
So I would like to leave an optional file reference in Xcode or add a new option like `allows_missing`.

**Comment by ra1028** [comment] 2019-04-02 11:18
Also, needs to run xcodegen & pod install twice if we installed SwiftGen via CocoaPods.

**Comment by yonaskolb** [comment] 2019-04-02 11:54
So some options would be:
- run `touch file.swift` before generating
- check in the swiftgen files
- add new option in `options.disabledValidations`. Something like `missingSourceFiles`
- add a flag to a target source so it adds a missing file to the project. Possible names:
	- `generated: true`
    - `allowMissing: true`
    - `transient: true`

**Comment by giginet** [comment] 2019-04-03 08:44
In our use case, we use Sourcery with XcodeGen.

Before building a source with Sourcery, we have to generate Xcode project with XcodeGen.
We used `optional` to make a reference to not existed file on 2.1.0, however, we can't use anymore.

Your new proposal seems to work well also in this case 👍

**Comment by giginet** [comment] 2019-04-03 08:48
I prefer to introduce `allowMissing` option.

**Comment by ra1028** [comment] 2019-04-03 09:48
Agreed.
I also prefer the `allowMissing` option.
If this opinion makes sense to @yonaskolb , I'll send a pull request within days.

**Comment by yonaskolb** [comment] 2019-04-03 09:54
That would be great @ra1028

**Comment by yonaskolb** [comment] 2019-04-04 12:38
After looking at the problem a bit more closely, I've decided to modify the change that was made in #527, by allowing missing file sources to be added when they are optional #557.
This was a regression that was caused and has now been treated like a bug. You can now continue to use `optional` for file sources. Directory sources will still not be added

**Closed** 2019-04-05 01:05 UTC
Labels: bug
