### ISSUE TITLE
--project command not work

### ISSUE THREAD

**Issue by chenjunpu** [yonaskolb/XcodeGen#447] opened 2018-11-26 08:42 UTC
Full `xcodegen generate` command `--project` not work

when i use: 

```shell
xcodegen --project ~/Downloads
```

```shell
📋  Loaded project:
  Name: Test
  Include:
    Libraries/environments.yml
  Targets:
    Test: iOS application
⚙️  Generating project...
⚙️  Writing project...
💾  Saved project to /Users/hb/Downloads/Test.xcodeproj
```

Log path is right, but xcodeproj still in the old path.
My xcodegen version: 2.0.0

**Comment by yonaskolb** [comment] 2018-12-01 07:19
Thanks for opening @chenjunpu. This was a regression that has been since fixed on master, and will be in the next release

**Closed** 2018-12-18 11:06 UTC
Labels: bug

**Comment by yonaskolb** [comment] 2018-12-18 11:43
Released in 2.1.0

**Comment by ninjazoete** [comment] 2019-01-02 19:04
Hi, I am using 2.1.0 and still when passing a path it does say it put the .xcodeproj there but it is always in the root of the spec.

**Comment by chenjunpu** [comment] 2019-01-03 02:01
Me too, still has this problem.
