### ISSUE TITLE
Link multiple Xcode projects

### ISSUE THREAD

**Issue by sbarow** [yonaskolb/XcodeGen#140] opened 2017-11-08 13:10 UTC
Is it possible or on the roadmap to be able to link multiple Xcode projects together? I think this would require using a workspace?

While you could possibly achieve this with `targets/frameworks` changing files in one of the `target/frameworks` doesn't trigger a rebuild of its dependencies?

Example:

- App
	- Libraries 
		- A
		- B
	- Features
		- C
		- D

**Comment by yonaskolb** [comment] 2017-11-08 13:21
Duplicate of #124 
Hi @sbarow. Yeah it's on the roadmap, but not in the immediate future. Unless someone wants to open a PR

**Closed by yonaskolb** 2017-11-08 13:21 UTC

**Comment by sbarow** [comment] 2017-11-08 13:30
Okay, I'll take a look.
