### ISSUE TITLE
Invalid scheme settings generated for custom watch

### ISSUE THREAD

**Issue by nvapp360** [yonaskolb/XcodeGen#764] opened 2020-01-30 01:21 UTC
When i created a watch scheme with different name, the scheme points to the {myApp}.app instead of {MyWatchApp}.app.

I didnt find any option to set the Executable* to point to the right .app file.

Executable* - _(Watch) Scheme -> Run -> Info -> Executable_

```
schemes:
  'Apple Watch':
     build:
       targets:
         Development: all
       parallelizeBuild: true
       buildImplicitDependencies: true
     run:
       config: Debug
       targets: MyWatchApp
```

This created the scheme, but the executable target was _{MyApp.app}_ instead of _{MyWatchApp.app}_

Can you point out if I am missing anything here?

**Comment by jcolicchio** [comment] 2020-05-07 14:38
Seems like a duplicate of #589 , it selects the first executable target using ASCII sorting; for now try changing the target name to ‘zMyApp’ or the watch target name to ‘AMyWatchApp’ — note case sensitivity, any uppercase sorts before any lowercase

**Comment by yonaskolb** [comment] 2020-05-31 03:21
Master now has an `run.executableName` that resolves this

**Closed by yonaskolb** 2020-05-31 03:21 UTC

**Comment by jcolicchio** [comment] 2020-05-31 04:56
🙇‍♂️ 🙏
