### ISSUE TITLE
Managing sources outside of the project folder

### ISSUE THREAD

**Issue by dmhts** [yonaskolb/XcodeGen#645] opened 2019-09-04 15:27 UTC
Hey @yonaskolb, first of all I wanted to thank you for this fantastic tool!

**Given:**

Having the stucture on the file system:
````
- ios_project
    - folder_1
    - folder_2
    ...
- shared_files
    - shared_folder_1
       - shared_file_1
    - shared_folder_2
    ...
````

and having this configuration:
````
sources:
      - "../shared_files/shared_folder_1/shared_file_1"
````
`xcodegen` generates the following project:
````
- ios_project
    - folder_1
    - folder_2
    - shared_folder_1
       - shared_file_1
    ...
````

**What I would want to have:**

The project with the following structure:
````
- ios_project
    - folder_1
    - folder_2
       - shared_folder_1
          - shared_file_1
    ...
````
or 
````
- ios_project
    - folder_1
    - folder_2
    - custom_group_name
       - shared_file_1
    ...
````

Meaning that I couldn't find a way to configure a specific path for "external" files in the resulting project. In the end, the files are located in the project relatively to the root, preserving their direct parent folder.

Did I miss something or is it an intended behaviour? Thanks.

**Comment by yonaskolb** [comment] 2019-09-27 14:10
Hi @dmhts. This is intended behaviour, as there is no good default for this.
This issue tracks having a custom group you can define, which would solve your issue https://github.com/yonaskolb/XcodeGen/issues/478
I'll close this for now

**Closed by yonaskolb** 2019-09-27 14:10 UTC
